### ISSUE TITLE
Adding tutorials?

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras-resources#21]
Custom layer tutorial: https://keunwoochoi.wordpress.com/2016/11/18/for-beginners-writing-a-custom-keras-layer/
Callback tutorial: https://keunwoochoi.wordpress.com/2016/07/16/keras-callbacks/

These are very simple ones, please add them if you think they're suitable.

**Comment by fchollet** [comment]
If this is still relevant, you can simply send a PR.

I don't check issues here much, sorry for the late reply!
